// Package content Code generated by swaggo/swag. DO NOT EDIT
package content

import "github.com/swaggo/swag"

const docTemplatecontent = `{
    "schemes": {{ marshal .Schemes }},
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Subject}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {},
    "securityDefinitions": {
        "content": {
            "type": "apiKey",
            "name": "Content-Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfocontent holds exported Swagger Info so clients can modify it
var SwaggerInfocontent = &swag.Spec{
	Version:          "v0.0.1",
	Host:             "localhost:8888",
	BasePath:         "",
	Schemes:          []string{"http", "https"},
	Title:            "Tool Content-API 文档",
	Description:      "Tool 服务",
	InfoInstanceName: "content",
	SwaggerTemplate:  docTemplatecontent,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfocontent.InstanceName(), SwaggerInfocontent)
}
