host: localhost:8888
info:
  contact: {}
  description: Aurora 建站
  title: Aurora Content-API 文档
  version: v0.0.1
paths: {}
produces:
- application/json
schemes:
- http
- https
securityDefinitions:
  content:
    in: header
    name: Content-Authorization
    type: apiKey
swagger: "2.0"
