server:
  port: 8889
  # 运行模式，dev/prod
  mode: dev
  # 缓存模式，memory/redis
  cache: memory
datasource:
  type: mysql
  url: test:123456@tcp(test.nineya.com:3306)/test_tool?charset=utf8mb4&parseTime=True&loc=Local
#  url: root:LSWang.361654768@tcp(test.nineya.com:3306)/tool?charset=utf8mb4&parseTime=True&loc=Local
  max-idle-conns: 10
  max-open-conns: 1000
  use-cache: true
  cache-size: 1000
  show-sql: true
redis:
  db: 8889
  host: 'test.nineya.com:6379'
  password: '361654768'
jwt:
  signing-key: 'ai-software-copyright-server'
  expires-time: 604800
  buffer-time: 86400
weixin:
  merchant:
    mchid: 1697924723
    api-v3-key: eS6oL9pD1eC5vM6wN9sG2aU8gG9zQ9sK
    serial-no: 6A38DD3B7C5405D3A3421BA2DCC713AC902273AB
    private-key-path: apiclient_key.pem
    notify-url: https://tool.nineya.com/api/user/public/wxNotify/pay
  mini-program:
    blogger-helper:
      appid: wx4af5d518ac7bf610
      secret: 5122bb6faf37b2c4c1eaaf80482c64fa
    traffic-toolbox:
      appid: wx058e0477e9177d83
      secret: e290f0fba8a4725b4c58ccb242a09a35
    operation-helper:
      appid: wxe58c9e5384ba0953
      secret: 26e9faa185f3dc2337948f0ff14afc7a
    wechat-toolbox:
      appid: wxffd5b43362a00597
      secret: e0a74d407a6dc894e43ae21250e6fe39
    netdisk-helper:
      appid: wx75162c9d66cbba20
      secret: e46d2a66609396b2f1673bf700144878
tool:
  image:
    allow-unknown-bucket: false
    default-bucket: default
    buckets:
      - blog
      - user
      - qrcode
    download-path: http://192.168.31.162:8889/image
plugin:
  zhipu-ai:
    apikey: 9c15b8f0ab5739aaa02ea772a9a2a34f.BYBizlMFhcTWXYcv
  mail:
    host: smtp.ym.163.com
    port: 994
    username: blog@nineya.com
    password: LSWang.361654768
    from: 玖涯工具
    admin-mail: lsw@nineya.com
  quark:
    user-id: 2
    cookie: "b-user-id=8bc93ea7-1288-bff4-a7bd-eade22afe3ed; __sdid=AARJR3ELDl5HNQx3MfwZ/FVBEL6JAQynud7T679BwKEtYzs5acQzh9UTFh4C1RJ9a1w=; _UP_A4A_11_=wb96c10a839c4083aaeb0f41fbd89b0b; xlly_s=1; _UP_D_=pc; __pus=76bab381ea4671627cf61a86460f9734AAQsVHik1srK4ofTWjJhNyHB0h4elVQ2ixO8ZmRUcKUg4kmJz93VkUNLwEn8575ClfQpSS/aMQAB7IlsPpYjQCcf; __kp=29e50210-d0ef-11ef-9c01-fd76aedd8f7d; __kps=AATc0kMB5zh8vxNnkiPRKJkN; __ktd=A1EmKlJ1e+trSqM7XGrJTw==; __uid=AATc0kMB5zh8vxNnkiPRKJkN; __puus=effebc82f237fdd6cd9a8174e78a1ec8AARpLqHBl4MMJ0BL7IISaN0+orWuDX0dzMYujGHyftsgah/Jv/K+S50WqWj1gwGoJNEVdMGo/0izw69a7QAXFK4gMbIa3IYM76oDZa/ptXLuH86vm1QuhK6mNc97OiyApaKID0UUSURF4f4DZ5ztuvjQSxR+/t/c02T8Sc5KjbNYLNMfQ8lhNZ2lq/vvWOIyFNDR15wz4Ox2udiuUViGCp5n; isg=BAsLmA6q6FbQNjTsl5K_JdL6mq_1oB8i_6hbsn0AX8qqnCX-BXBTc4z0dpxyvHca; tfstk=gRpobCqyaQ5SibTTyEWS1IPRISlY1T65La8dJwKF8gbfzwhWvIXeXejdeHuWtExFlwRLawy30eSzULhCLZYDlU28pT78x9xHSefIVwQF-eKewmHtB3t5d9RnWAHt18lXLUjF46oFggIIDgRZjEA5d9utkSeFNAXB5dq51B-qmMI38z8FaoyVlMFP8e7PgrSGf97e8e520Gj1Yy7PLi5VlMWF8eWEmtlrKJ7MLCJqodA3bf80UzScZN-PoRxXnguFjA_QLJJcqnbH4I2ULKjlZp1L1ULfwB-11LKnK-6JjIWVxpiatwfMTLB2UqkNG6J2ui8-vWsDtHJ1F_ZQdFXk-1JPikyCU975niJZv5_vnaLeEsoTI6B2B1WyMjgR9TjM8LTuxJ8wDhp5Gp0guwORftSHdcPh-6SrMSPZiDwC0Dp4OW1PcibTNR1Sf06nHvomm5G5ais1Wmm0O05PciAEmmVwo_SfV35.."
    to-pdir-fid: 6a2267b3975d484c99f6078d1668cb95
  baidu:
    user-id: 2
    cookie: "PANWEB=1; PSTM=1755118336; BIDUPSID=B8340D8433B79E34490755B892A91E0D; Hm_lvt_95fc87a381fad8fcb37d76ac51fefcea=1755118346; BAIDUID=2F1C89FA1EFBF66D658C3B8287726077:SL=0:NR=10:FG=1; newlogin=1; MAWEBCUID=web_qmbpnrVEOIhkgGKVXZFDJTlJqPvAukvfgUalVdATbkoOMexaNq; BDUSS=Q5RVB0RzV2dllRVXVlSmhSWEhpcnhFTk5WTFVwMDBYb0VQenh6cUZUTERkczlvRUFBQUFBJCQAAAAAAAAAAAEAAADUJ3SS6eTRqbuwvvex8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMPpp2jD6adoRm; BDUSS_BFESS=Q5RVB0RzV2dllRVXVlSmhSWEhpcnhFTk5WTFVwMDBYb0VQenh6cUZUTERkczlvRUFBQUFBJCQAAAAAAAAAAAEAAADUJ3SS6eTRqbuwvvex8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMPpp2jD6adoRm; BDSFRCVID=KEkOJeC627zQvO5s6YAeJnbi0jwtwpbTH6f3LD6NxOnlVc0gAC2nEG0PdM8g0Kub6jBrogKKKgOTHICF_2uxOjjg8UtVJeC6EG0Ptf8g0x5; H_BDCLCKID_SF=tbC8VCD5JKL3HJ3NhRO5q4D_MfOtetJyaR3-0InvWJ5WqR7j3POS36Kyj4RHtUTXKDKjLU7RJCJ_ShbXKxoH3T_-qJQfKq-OHGcW3x3a3l02V-bI0MKVKPPVjx6GLtRMW23i0h7mWpTTsxA45J7cM4IseboJLfT-0bc4KKJxbnLWeIJEjjC5Djc-DHtftjnK5KTXLP88KJjEe-Kk-PnVepk75tnZKRvHa2vU0nRCJt8-HfbXy4TDMj83Bn-tJP6n3N5HKRj6t4IVVt3I3TAV34P_3po405OTbIcT5j6b2b_-jloKhPJvyUPsXnO7BxJlXbrtXp7_2J0WStbKy4oTjxL1Db3JKjvMtgDtVD8hfCIaMIL4ePKK-CCV-frb-C62aKDsah5oBhcqEIL4jn6G5xR0KNjk34QZaDr0onc5bP32HxbSj4D5XM3BXl792t7pKbRM5l8-aq5nhMJgXj7JDMP0-GjB3Jjy523iab3vQpnzEpQ3DRoWXPIqbN7P-p5Z5mAqKl0MLPbtbb0x25_0-nDSHH8DJTKq3e; csrfToken=lbdVEWD8e4c3CIvIsDHSRRXQ; STOKEN=e2b54fc010e6f447575526f4aca46c06bc81b0777e5d4c0f1c26101c47b16686; BDCLND=GRu%2BL4wtRmYFuKGqbUbQrnRKlZgpPRiK; Hm_lvt_7a3960b6f067eb0085b7f96ff5e660b0=1755117416,1756110717; HMACCOUNT=52694ED29412F643; Hm_lvt_182d6d59474cf78db37e0b2248640ea5=1755167442,1756110745; Hm_lpvt_7a3960b6f067eb0085b7f96ff5e660b0=1756233342; H_PS_PSSID=62325_63145_63326_63947_64248_64360_64363_64437_64450_64460_64476_64503_64515_64521_64543_64560_64573_64585_64600_64635_64660_64669_64711_64741_64743_64738_64748_64823; H_WISE_SIDS=62325_63145_63326_63947_64248_64360_64363_64437_64450_64460_64476_64503_64515_64521_64543_64560_64573_64600_64635_64660_64669_64711_64741_64743_64738_64748_64823; BAIDUID_BFESS=2F1C89FA1EFBF66D658C3B8287726077:SL=0:NR=10:FG=1; BDSFRCVID_BFESS=KEkOJeC627zQvO5s6YAeJnbi0jwtwpbTH6f3LD6NxOnlVc0gAC2nEG0PdM8g0Kub6jBrogKKKgOTHICF_2uxOjjg8UtVJeC6EG0Ptf8g0x5; H_BDCLCKID_SF_BFESS=tbC8VCD5JKL3HJ3NhRO5q4D_MfOtetJyaR3-0InvWJ5WqR7j3POS36Kyj4RHtUTXKDKjLU7RJCJ_ShbXKxoH3T_-qJQfKq-OHGcW3x3a3l02V-bI0MKVKPPVjx6GLtRMW23i0h7mWpTTsxA45J7cM4IseboJLfT-0bc4KKJxbnLWeIJEjjC5Djc-DHtftjnK5KTXLP88KJjEe-Kk-PnVepk75tnZKRvHa2vU0nRCJt8-HfbXy4TDMj83Bn-tJP6n3N5HKRj6t4IVVt3I3TAV34P_3po405OTbIcT5j6b2b_-jloKhPJvyUPsXnO7BxJlXbrtXp7_2J0WStbKy4oTjxL1Db3JKjvMtgDtVD8hfCIaMIL4ePKK-CCV-frb-C62aKDsah5oBhcqEIL4jn6G5xR0KNjk34QZaDr0onc5bP32HxbSj4D5XM3BXl792t7pKbRM5l8-aq5nhMJgXj7JDMP0-GjB3Jjy523iab3vQpnzEpQ3DRoWXPIqbN7P-p5Z5mAqKl0MLPbtbb0x25_0-nDSHH8DJTKq3e; delPer=0; PSINO=1; BDORZ=B490B5EBF6F3CD402E515D22BCDA1598; BA_HECTOR=a1al0181848h240l0hak248001040g1kav40h24; ZFY=I:BS6G7vEQxc0O3zL4GlcbLJ9EQlb5Qpf:AUNzC9uU:AhU:C; Hm_lpvt_182d6d59474cf78db37e0b2248640ea5=1756342489; ndut_fmt=C2437E4DB426F82B3FB6D780552C75CFB3D01C5643055DB90667ACA39E45C3E4; ab_sr=1.0.1_NTZiZGY3ZWI3MGM2NDM1ZTM4ODJkMmRiMTFjYmNiNDgxNTFhMGM0YjgyZWJkNmIyMzRiNmMzNGI5YmFhMzU1ZGJjYjczMTJhNjczMzY3MzQxY2Q4MWE5MDc3YTQ0MWQ3ZmYyOTdlOWU1MDE5YjM4ZmE0MjJmZjE2YTRiYWJmZmMwMDE3YjNiN2QwNzM0NDU3YmY2NGE5MjI3ZjEzYjkzNTk1MDdkOWJjM2ZmZjVjMmJjZjAyMzYwZmJkYjdhOGJl; PANPSC=8872013078706161611%3AnHZOtuqy9au7UJExKM2vAVcS2d9ns3O5C61tf8CKQkgCJNPOYqkdQPEZy5xVYxZqaxrrYILGqsUL5EYDuI9ZvuNHiOwr%2ByPWOg9ifdcaUVcaVGihM6XIbgJxNIdv5MxWbXEHvm4MBGkwsmEDsADAQOArxaIRi85uORNKcBmLBrSjF0P%2Bkk%2BEc2KmXcvc2dd5bH2fO7vFsi%2FlL5GDz11%2BrwIs3OYQGyTtbn6W6s2p0PaeBYyhukOB9lhsPDr2clknKNjk%2B%2Fjfniw8hOASVh2HM6iuFTJnfVq9mVe%2FV4MCjfkE4F9K1nABc%2FPfe2u0ilFOJKrQ2%2BvjtVOSsVZaqyA8TA%3D%3D"
    to-path: "/搜索转存"
    pwd: 6666
logger:
  path: logs
  log-in-console: true